### ISSUE TITLE
I fixed this library and added a bunch of features: pymetasploit3

### ISSUE THREAD

**Issue by DanMcInerney** [allfro/pymetasploit#32]
If anyone is having trouble with this library I highly recommend testing out my updated version of it for python3 which added a bunch of new features such as running modules and returning their output. 

https://github.com/DanMcInerney/pymetasploit3

Please let me know of any issues that arise as I plan on making this the tested and maintained standard python metasploit library.

**Comment by allfro** [comment]
Thank you for your contribution. We just merged PR #37 which addresses the migration to py3 thanks to the contributions of wonderful people such as yourself and others. Hopefully the latest version in master addresses your needs.
